var utility=require('../Utility/new')
const readline=require('readline-sync')
var a=readline.question('enter the a value')
var b=readline.question('enter the b value')
var c=readline.question('enter the b value')
utility.quadratic(a,b,c)
